-- MySQL Script generated by MySQL Workbench
-- 08/21/15 10:02:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sesilab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sesilab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sesilab` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sesilab` ;

-- -----------------------------------------------------
-- Table `sesilab`.`Mahasiswa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sesilab`.`Mahasiswa` (
  `NRP` VARCHAR(11) NOT NULL,
  `Nama` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(15) NOT NULL DEFAULT 'Praktikan',
  PRIMARY KEY (`NRP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sesilab`.`Kelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sesilab`.`Kelas` (
  `IdKelas` VARCHAR(10) NOT NULL,
  `MataKuliah` VARCHAR(45) NULL,
  `Kelas` VARCHAR(45) NULL,
  PRIMARY KEY (`IdKelas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sesilab`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sesilab`.`Schedule` (
  `IdSch` INT NOT NULL AUTO_INCREMENT,
  `JamMulai` DATETIME NOT NULL,
  `JamSelesai` DATETIME NOT NULL,
  `Materi` VARCHAR(45) NOT NULL,
  `Penugasan` LONGTEXT NULL,
  `DeadlineTugas` DATETIME NULL,
  `Kelas_IdKelas` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`IdSch`, `Kelas_IdKelas`),
  INDEX `fk_Schedule_Kelas1_idx` (`Kelas_IdKelas` ASC),
  CONSTRAINT `fk_Schedule_Kelas1`
    FOREIGN KEY (`Kelas_IdKelas`)
    REFERENCES `sesilab`.`Kelas` (`IdKelas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sesilab`.`KelasMahasiswa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sesilab`.`KelasMahasiswa` (
  `Mahasiswa_NRP` VARCHAR(11) NOT NULL,
  `Kelas_IdKelas` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Mahasiswa_NRP`, `Kelas_IdKelas`),
  INDEX `fk_Mahasiswa_has_Kelas_Kelas1_idx` (`Kelas_IdKelas` ASC),
  INDEX `fk_Mahasiswa_has_Kelas_Mahasiswa_idx` (`Mahasiswa_NRP` ASC),
  CONSTRAINT `fk_Mahasiswa_has_Kelas_Mahasiswa`
    FOREIGN KEY (`Mahasiswa_NRP`)
    REFERENCES `sesilab`.`Mahasiswa` (`NRP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mahasiswa_has_Kelas_Kelas1`
    FOREIGN KEY (`Kelas_IdKelas`)
    REFERENCES `sesilab`.`Kelas` (`IdKelas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sesilab`.`Absensi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sesilab`.`Absensi` (
  `Mahasiswa_NRP` VARCHAR(11) NOT NULL,
  `Schedule_IdSch` INT NOT NULL,
  `Schedule_Kelas_IdKelas` VARCHAR(10) NOT NULL,
  `Status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Mahasiswa_NRP`, `Schedule_IdSch`, `Schedule_Kelas_IdKelas`),
  INDEX `fk_Mahasiswa_has_Schedule_Schedule1_idx` (`Schedule_IdSch` ASC, `Schedule_Kelas_IdKelas` ASC),
  INDEX `fk_Mahasiswa_has_Schedule_Mahasiswa1_idx` (`Mahasiswa_NRP` ASC),
  CONSTRAINT `fk_Mahasiswa_has_Schedule_Mahasiswa1`
    FOREIGN KEY (`Mahasiswa_NRP`)
    REFERENCES `sesilab`.`Mahasiswa` (`NRP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mahasiswa_has_Schedule_Schedule1`
    FOREIGN KEY (`Schedule_IdSch` , `Schedule_Kelas_IdKelas`)
    REFERENCES `sesilab`.`Schedule` (`IdSch` , `Kelas_IdKelas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sesilab`.`FileStore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sesilab`.`FileStore` (
  `idFile` INT NOT NULL AUTO_INCREMENT,
  `NamaFile` VARCHAR(45) NOT NULL,
  `File` MEDIUMBLOB NULL,
  `WaktuUpload` DATETIME NULL,
  PRIMARY KEY (`idFile`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
